---
# tasks file for ansible-role-solr

- name: Load a variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: manage storage devices
  include_tasks: system/manage_storage.yml
  when: manage_storage

- name: Choose platform based task
  include_tasks: '{{ platform }}'
  with_first_found:
    - 'system/{{ ansible_os_family }}.yml'
    - 'system/not-supported.yml'
  loop_control:
    loop_var: platform

- name: solr backup task
  include_tasks: system/backup.yml

- name: solr dns entry
  include_tasks: system/dns.yml
