---
# tasks file for ansible-role-solr

- name: get instance_id
  uri:
    url: http://169.254.169.254/latest/meta-data/instance-id
    return_content: yes
  register: instance_data

- name: Update our system
  yum:
    name: "*"
    state: latest

- name: Reconfigure our system time sync
  include: system/configure_time.yml

- name: Install java
  include: system/jdk.yml

- name: Load a variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: manage storage devices
  include_tasks: system/manage_storage.yml

- name: install solr
  include_tasks: system/install.yml

- name: Choose platform based task
  include_tasks: "{{ platform }}"
  with_first_found:
    - "system/{{ ansible_os_family }}.yml"
    - "system/not-supported.yml"
  loop_control:
    loop_var: platform
