---

- name: set dns facts
  set_fact:
    record_name: "{{ solr_dns_record }}.{{ dns_zone_name }}"

- name: add solr internal dns host name
  route53:
    state: present
    hosted_zone_id: "{{ dns_zone_id }}"
    record: "{{ record_name }}"
    zone: "{{ dns_zone_name }}"
    type: A
    ttl: 300
    value: "{{ ansible_default_ipv4.address }}"
    overwrite: yes
    private_zone: yes
    wait: yes
