---
- name: "create mount path for {{ solr_volume_name }}"
  file:
    state: "directory"
    path: "{{ solr_base_path }}"

- name: Read device information
  parted: device={{ solr_device_name }} unit=MiB
  register: sdb_info

- name: "create partition on {{ solr_volume_name }}"
  parted:
    device: "{{ solr_device_name }}"
    number: 1
    label: "gpt"
    part_start: "0%"
    part_end: "100%"
    name: "data"
    state: "present"
  when: not sdb_info.partitions

- name: "format partition on {{ solr_volume_name }}"
  filesystem:
    dev: "{{ solr_device_name }}"
    fstype: "{{ solr_volume_fs_type }}"
  when: not sdb_info.partitions

- name: "mount the partition for {{ solr_volume_name }}"
  mount:
    path: "{{ solr_base_path }}"
    src: "{{ solr_device_name }}"
    fstype: "{{ solr_volume_fs_type }}"
    state: "mounted"
